### ISSUE TITLE
Handle errors better if error is thrown inside consumes function

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/fastkafka#111]
How to replicate?
Follow the tutorial at https://fastkafka.airt.ai/#tutorial but don't specify the model.
Run [testing code](https://fastkafka.airt.ai/#testing-the-service)

![Image](https://user-images.githubusercontent.com/7011056/223126922-413a307a-6de6-4fe2-bce7-913af98835b7.png)

**Comment by davorrunje** [comment]
We'll handle this in #121
