### ISSUE TITLE
Rename existing functions into start and stop and add lifespan handler

### ISSUE THREAD

**Issue by davorrunje** [airtai/fastkafka#117]
https://www.linkedin.com/posts/tiangolo_fastapi-activity-7038907638331404288-Oar3/?utm_source=share&utm_medium=member_ios

**Comment by Sternakt** [comment]
- [x] Rename startup and shutdown functions
- [x] Implement lifespan handler __aenter__ and __aexit__ calls
- [ ] Implement lifespan handler tests
- [ ] Write a lifespan handler guide
