### ISSUE TITLE
Unexpected internal error: [Errno 2] No such file or directory: 'npx'

### ISSUE THREAD

**Issue by davorrunje** [airtai/fastkafka#158]
### Discussed in https://github.com/airtai/fastkafka/discussions/138

<div type='discussions-op-text'>

<sup>Originally posted by **fangorntreabeard** March 13, 2023</sup>
I really like this framework, but one mistake haunts me. Tell us how to fix it:
Unexpected internal error: [Errno 2] No such file or directory: 'npx'</div>

**Comment by Sternakt** [comment]
Added checks for npx and npx version and verbose Exceptions when npx is not found or major version is too low
