### ISSUE TITLE
Currently not suitable for work with several brokers

### ISSUE THREAD

**Issue by Gerleff** [airtai/fastkafka#309]
Best expected result:
- I can provide several bootstrap_servers and consume messages for them;
- I can optionally map producers with bootstrap_servers, each not mapped producer sends messages to first provided bootstrap_server by default;
- I can choose whether to consume messages concurrently (in container) or in parallel (in virtual env with usage of processes).

For the project I'm currently working on, if I wanna use fastkafka at current state, I need to set N containers up for N Kafka brokers, which does not suit well.

**Comment by Gerleff** [comment]
Hi

I have en error occurring, if execute `fastkafka run ... --kafka-broker staging ...`:

Traceback:
...
`
/site-packages/fastkafka/_application/app.py:102 in <dictcomp>                                   │
                                                                                                 │
│    99 │   else:                                                                                  │
│   100 │   │   retval = KafkaBrokers(                                                             │
│   101 │   │   │   brokers={                                                                      │
│ ❱ 102 │   │   │   │   k: KafkaBroker.parse_raw(                                                  │
│   103 │   │   │   │   │   v.json() if hasattr(v, "json") else json.dumps(v)                      │
│   104 │   │   │   │   )                                                                          │
│   105 │   │   │   │   for k, v in kafka_brokers.items()                                          │
│                                                                                                  │`

...

`
│ │ .0 = <dict_itemiterator object at 0x1101be7f0>                          │                      │
│ │  k = 'Transaction Kafka'                                                │                      │
│ │  v = {                                                                  │                      │
│ │      │   'url': [                                                       │                      │
│ │      │   │   '127.0.0.1:9092',                                          │                      │
│ │      │   │   '127.0.0.1:9093',                                          │                      │
│ │      │   │   '127.0.0.1:9094'                                           │                      │
│ │      │   ],                                                             │                      │
│ │      │   'description': 'Transaction kafka broker',                     │                      │
│ │      │   'port': 9092                                                   │                      │
│ │      }                                                                  │                      │
ValidationError: 1 validation error for KafkaBroker
url
  str type expected (type=type_error.str)
`

**Comment by Gerleff** [comment]
It would work, actually, if implemented ) 

My minimal requirement is to execute `fastkafka run ... --kafka-broker staging ...` 

with

```
kafka_brokers = {'staging': {'url': ['url1', 'url2', 'url3'], ...}}
app = FastKafka(kafka_brokers= kafka_brokers)
```

and receive messages from each url.

**Comment by davorrunje** [comment]
Yeah, that was just the sketch of the idea :)

It is scheduled for this sprint, it should be finished by this Friday.
