### ISSUE TITLE
Provide proxy/router to support module-distributed application

### ISSUE THREAD

**Issue by Gerleff** [airtai/fastkafka#321]
Currently using 

```
class FastKafkaRouter:
    """Proxy-app for FastKafka."""

    def __init__(self):
        self._consumers_store = {}
        self._producers_store = {}

    consumes = FastKafka.consumes
    produces = FastKafka.produces

    def transfer_handlers_to(self, app: FastKafka):
        """Transfer handlers into FastKafka application."""
        app._consumers_store.update(self._consumers_store)
        app._producers_store.update(self._producers_store)
        for attr, value in vars(self).items():
            if attr not in ("_consumers_store", "_producers_store"):
                setattr(app, attr, value)


# module <consumers/topic_handlers.py>
router = FastKafkaRouter()

@router.consumes(topic=...)
async def on_input(msg):
    ...
    
# module <fastkafka_app.py>
from consumers.topic_handlers import router

app = FastKafka(...)
router.transfer_handlers_to(app)
```

That helps support such distributed architecture.

<img width="504" alt="Снимок экрана 2023-05-24 в 15 46 38" src="https://github.com/airtai/fastkafka/assets/69368761/faf24f73-f65b-4fb5-93a2-90c19f26f980">

**Comment by Gerleff** [comment]
Updated example

**Comment by Gerleff** [comment]
[UPD] Works well with consumers, but doesn't work with producers in provided example.

**Comment by davorrunje** [comment]
You can start FastKafka using FastAPI and we have a new convenience method and a guide on how to do it in the upcoming release (RC is planned for tomorrow):

https://fastkafka.airt.ai/docs/next/guides/Guide_32_Using_fastapi_to_run_fastkafka_application

Would that be an option for you?

**Comment by davorrunje** [comment]
Closing for now due to FastAPI alternative.
