### ISSUE TITLE
Provide optional "description" argument to consumes and produces decorator

### ISSUE THREAD

**Issue by Gerleff** [airtai/fastkafka#323]
In team we have the rule to document code basis in Russian, but all the docs we provide must be in English.
Autogeneration of docs is using __doc__ attribute of function to generate description.

Current way to achieve the goal:
```
@producers_router.produces(topic="transaction.response.order_status")
async def exchange_orders_status_producer(message: OrderStatus) -> OrderStatus:
    """Продюсер по топику transaction.response.order_status."""
    return message

exchange_orders_status_producer.__doc__ = "Publish exchange_order's status"
```

Preferable solution:
```
@producers_router.produces(topic="transaction.response.order_status", description="Publish order status")
async def exchange_orders_status_producer(message: OrderStatus) -> OrderStatus:
    """Продюсер по топику transaction.response.order_status."""
    return message
```

Thanks for response =)

**Comment by Gerleff** [comment]
Works well for consumers, and does not for producers.

**Comment by Sternakt** [comment]
I'll reopen the issue, see what went wrong and we'll do a patch for this in the next couple of days.

Thanks for the quick feedback :)

**Comment by Sternakt** [comment]
Can you please explain what is failing for the producers, with code examples if possible.

For a simple app example:

```python
app = FastKafka(kafka_brokers=kafka_brokers)

@app.produces(description="Producer description in documentation")
async def to_hello_world(msg: str) -> HelloWorld:
    """This description should not show"""
    return HelloWorld(msg=msg)
```
The description "Producer description in documentation" is shown in the async docs for the producer.
