### ISSUE TITLE
consumer method: how to commit messages manually?

### ISSUE THREAD

**Issue by Felix-neko** [airtai/fastkafka#467]
Hi folks! And thank you for your great project.

I want to read messages from Kafka topic (wrapping my message processor with `consumes` decorator).

But I want not just to auto-commit messages, but to commit them manually -- and only if the message processing was correct (when my extra function that was processing their internal data did not throw any exception).

How can it be done? How can I commit messages manually -- and only when I really want to commit them?

---
Best,
Felix

**Comment by Sternakt** [comment]
Hi!

Unfortunately, the manual commit mechanism is not yet available in FastKafka.
It is in the plan to be done at one point, but I cannot tell exactly when this will be implemented, sorry for not having more detailed news and for the wait.
