### ISSUE TITLE
AsyncAPI export

### ISSUE THREAD

**Issue by davorrunje** [airtai/fastkafka#509]

**Comment by Sternakt** [comment]
documentation can be exported with `faststream docs gen _namespace_:_symbol_` and served with `faststream docs serve _namespace_:_symbol_`

We need to:

- [ ] Write and test and example for generating/serving the documentation
- [ ] Write a guide for generating/serving the documentation

**Comment by Lancetnik** [comment]
We already have tests for documentation generation in the `tests/asyncapi` directory
Probably, we just need to add a smoketest for the CLI command
Please, use `typer.invoke` for it
