### ISSUE TITLE
Add PyYAML to dependencies in pyproject.toml

### ISSUE THREAD

**Issue by rjambrecic** [airtai/fastkafka#601]
When you install:
`pip install faststream[kafka]`

and run:
`faststream run application:app`

you get:
`ModuleNotFoundError: No module named 'yaml'`

**Comment by Lancetnik** [comment]
We need no to add yaml to project dependencies: this is optional
I will review all imports to build project correct without it

**Comment by Lancetnik** [comment]
I know, usage derict `yaml` is a mistake
